---
name: Functions
author: Ad5001
version: "1.0"
api:
- 1.14.0
main: Ad5001\Functions\Main
commands: 
  function:
     description: "Create, manage and remove functions with this command"
     usage: "/function <sub-command> <function> parameters..."
     permission: func.command.function
permissions:
   func.command.function:
     default: op
     description: "Create, manage and remove functions with this command"
...
